# Generated by Django 5.0.3 on 2024-03-25 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobdescription', models.TextField()),
                ('qualifications', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('is_available', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
