# Generated by Django 5.0.3 on 2024-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movies', models.CharField(max_length=100)),
            ],
        ),
    ]
