# Generated by Django 5.0.3 on 2024-03-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='recruiter.newjob'),
        ),
    ]
